Handling honeybee.key file issues in cm-grasshopper

diff --git a/conf/docker/docker-compose.yaml b/conf/docker/docker-compose.yaml
--- a/conf/docker/docker-compose.yaml
+++ b/conf/docker/docker-compose.yaml
@@ -200,7 +200,8 @@ services:
   # https://hub.docker.com/r/cloudbaristaorg/cm-beetle
   # See https://github.com/cloud-barista/cm-beetle/blob/main/deployments/docker-compose/docker-compose.yaml#L156
   cm-beetle:
-    image: cloudbaristaorg/cm-beetle:0.2.0
+    #image: cloudbaristaorg/cm-beetle:0.2.0
+    image: cloudbaristaorg/cm-beetle:edge
     container_name: cm-beetle
     platform: linux/amd64
     ports:
@@ -268,7 +269,8 @@ services:
   # https://hub.docker.com/r/cloudbaristaorg/cm-honeybee
   # See https://github.com/cloud-barista/cm-honeybee/blob/main/server/docker-compose.yaml
   cm-honeybee:
-    image: cloudbaristaorg/cm-honeybee:0.2.0
+    #image: cloudbaristaorg/cm-honeybee:0.2.0
+    image: cloudbaristaorg/cm-honeybee:edge
     container_name: cm-honeybee
     platform: linux/amd64
     ports:
@@ -277,6 +279,8 @@ services:
       #- "8082:8082"
     depends_on:
       - cm-honeybee-agent
+    volumes:
+      - ./data/cm-honeybee/:/root/.cm-honeybee/:rw
     #network_mode: "host"
 
 
@@ -307,7 +311,8 @@ services:
   # https://github.com/cloud-barista/cm-cicada
   # https://hub.docker.com/r/cloudbaristaorg/cm-cicada
   cm-cicada:
-    image: cloudbaristaorg/cm-cicada:0.2.0
+    #image: cloudbaristaorg/cm-cicada:0.2.0
+    image: cloudbaristaorg/cm-cicada:edge
     container_name: cm-cicada
     restart: always
     ports:
@@ -401,7 +406,8 @@ services:
   # https://hub.docker.com/r/cloudbaristaorg/cm-grasshopper
   # See https://github.com/cloud-barista/cm-grasshopper/blob/main/docker-compose.yaml
   cm-grasshopper:
-    image: cloudbaristaorg/cm-grasshopper:0.2.0
+    #image: cloudbaristaorg/cm-grasshopper:0.2.0
+    image: cloudbaristaorg/cm-grasshopper:edge
     container_name: cm-grasshopper
     restart: always
     ports:
@@ -409,12 +415,25 @@ services:
     depends_on:
       - cm-honeybee
     volumes:
-      - ./conf/cm-grasshopper/conf:/conf
-      - ./conf/cm-grasshopper/honeybee.key:/root/.cm-grasshopper/honeybee.key:ro
-      - ./data/cm-grasshopper/CM-GRASSHOPPER.db:/CM-GRASSHOPPER.db:rw
+      - ./conf/cm-grasshopper/conf:/root/.cm-grasshopper/conf
+      #- ./data/cm-honeybee/:/root/.cm-grasshopper/:ro
+      - ./data/cm-honeybee/:/root/.cm-grasshopper/honeybee:ro
+      - ./data/cm-grasshopper/log:/root/.cm-grasshopper/log:rw
+      #- ./conf/cm-grasshopper/honeybee.key:/root/.cm-grasshopper/honeybee.key:ro
+      #- ./data/cm-honeybee/honeybee.key:/root/.cm-grasshopper/honeybee.key:ro
       - ./data/cm-grasshopper/software_temp:/software_temp:rw
       - ./data/cm-grasshopper/software_log:/software_log:rw
       - ./data/cm-grasshopper/playbook:/playbook/:rw
+    command: >
+      /bin/sh -c "
+        if [ ! -f /root/.cm-grasshopper/honeybee/honeybee.key ]; then
+          echo 'honeybee.key not found, exiting...';
+          exit 1;
+        else
+          cp /root/.cm-grasshopper/honeybee/honeybee.key /root/.cm-grasshopper/ && echo 'Finished copying the honeybee.key file.';
+          /cm-grasshopper;
+        fi
+      "
     #network_mode: "host"
 
 
